/*
 * File: app/view/AfterMarket.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AfterMarket', {
    extend: 'Ext.form.Panel',
    alias: 'widget.aftermarket',

    config: {
        ui: 'dark',
        scrollable: 'vertical',
        iconCls: 'insurance',
        title: 'After Market',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'After Market',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 100,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 92,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 98,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 101,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                html: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        height: 30,
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                html: 'After Market',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 287,
                                inputCls: 'textBlack',
                                label: 'Supplier:',
                                labelCls: 'normalLabelText',
                                labelWidth: '32%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 8
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 226,
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Invoice Price:',
                                labelCls: 'normalLabelText',
                                labelWidth: '55%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 8
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 212,
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Commission: ',
                                labelCls: 'normalLabelText',
                                labelWidth: '55%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'excluding GST'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 15,
                html: ''
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                html: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        height: 30,
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Other Insurance',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 287,
                                inputCls: 'textBlack',
                                label: 'Supplier:',
                                labelCls: 'normalLabelText',
                                labelWidth: '35%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 8
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 226,
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Invoice Price:',
                                labelCls: 'normalLabelText',
                                labelWidth: '55%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 8
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 212,
                                clearIcon: false,
                                inputCls: 'textBlack',
                                label: 'Commission: ',
                                labelCls: 'normalLabelText',
                                labelWidth: '55%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'excluding GST'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 15,
                html: ''
            },
            {
                xtype: 'container',
                html: '',
                items: [
                    {
                        xtype: 'panel',
                        height: 35,
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 42,
                                width: 288
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 39,
                                html: 'Total:',
                                width: 53
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 20,
                                width: 91
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 39,
                                html: '0.0 ',
                                width: 53
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 20,
                                width: 155
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: '0.0 '
                            }
                        ]
                    }
                ]
            }
        ]
    }

});