/*
 * File: app/view/Asset.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Asset', {
    extend: 'Ext.form.Panel',
    alias: 'widget.asset',

    config: {
        iconCls: 'assets',
        title: 'Asset',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Asset',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 96,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 85,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 89,
                        icon: 'images/next1.png',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 45,
                items: [
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'Database:',
                        width: 95
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 195,
                        inputCls: 'textBlack',
                        label: 'Car/Commercial',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '75%',
                        name: 'assetdatabasegroup',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 175,
                        inputCls: 'textBlack',
                        label: 'Motor Cycle',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '70%',
                        name: 'assetdatabasegroup'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 8
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        height: 30,
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Vehicle',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 15
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 189,
                                inputCls: 'textBlack',
                                label: 'Year:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '35%',
                                options: [
                                    {
                                        value: 2003,
                                        text: 2003
                                    },
                                    {
                                        value: 2004,
                                        text: 2004
                                    },
                                    {
                                        value: 2005,
                                        text: 2005
                                    },
                                    {
                                        value: 2006,
                                        text: 2006
                                    },
                                    {
                                        value: 2007,
                                        text: 2007
                                    },
                                    {
                                        value: 2008,
                                        text: 2008
                                    },
                                    {
                                        value: 2009,
                                        text: 2009
                                    },
                                    {
                                        value: 2010,
                                        text: 2010
                                    },
                                    {
                                        value: 2011,
                                        text: 2011
                                    },
                                    {
                                        value: 2012,
                                        text: 2012
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 10
                            },
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 280,
                                inputCls: 'textBlack',
                                label: 'Make:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '35%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'Holden',
                                        text: 'Holden'
                                    },
                                    {
                                        value: 'Honda',
                                        text: 'Honda'
                                    },
                                    {
                                        value: 'Isuzu',
                                        text: 'Isuzu'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 10
                            },
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 251,
                                inputCls: 'textBlack',
                                label: 'Body Type:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'Sedan',
                                        text: 'Sedan'
                                    },
                                    {
                                        value: 'Utiliy',
                                        text: 'Utility'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 161,
                                inputCls: 'textBlack',
                                label: 'Model:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                width: 75,
                                text: 'Model'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 10
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 230,
                                inputCls: 'textBlack',
                                label: 'Registration No:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '60%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 10
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 255,
                                inputCls: 'textBlack',
                                label: 'VIN Number:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '45%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Badge Desc:',
                                width: 124
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 0,
                                width: 114
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 35
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Cylinders:',
                                width: 124
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: 1,
                                width: 83
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 22
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Fuel Type:',
                                width: 124
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 0,
                                width: 94
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Transmission:',
                                width: 124
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 0,
                                width: 124
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 27
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Redbook DataBase: Last Updated:  ',
                                width: 294
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '06/06/2012',
                                width: 124
                            }
                        ]
                    }
                ]
            }
        ]
    }

});