/*
 * File: app/view/CCI.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CCI', {
    extend: 'Ext.form.Panel',
    alias: 'widget.cci',

    config: {
        height: 1000,
        ui: 'light',
        scrollable: 'vertical',
        iconCls: 'insurance',
        title: 'CCI',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'CCI',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 94,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 88,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 89,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            },
            {
                xtype: 'container',
                height: 45,
                width: 740,
                items: [
                    {
                        xtype: 'selectfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 189,
                        inputCls: 'textBlack',
                        label: 'Badge:',
                        labelCls: 'normalLabelText',
                        labelWidth: '40%',
                        name: 'badgepremium',
                        options: [
                            {
                                value: 'A',
                                text: 'A'
                            },
                            {
                                value: 'M',
                                text: 'M'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 21
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 25
                    },
                    {
                        xtype: 'numberfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 234,
                        inputCls: 'textBlack',
                        label: 'Premium: $',
                        labelCls: 'normalLabelText',
                        labelWidth: '45%',
                        name: 'badgepremium'
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 59
                    },
                    {
                        xtype: 'image',
                        docked: 'left',
                        height: 25,
                        html: '',
                        width: 74,
                        src: 'images/statusfalse.png'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                height: 45,
                items: [
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        inputCls: 'textBlack',
                        label: 'Private',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '60%',
                        name: 'privatebusiness',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        inputCls: 'textBlack',
                        label: 'Business',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '60%',
                        name: 'privatebusiness'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                height: 320,
                items: [
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 320,
                        width: 290,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                width: '99%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Insurance Product',
                                        padding: 5,
                                        width: 166
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'Joint Cover',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'Balloon Cover',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'Life:',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        width: 20
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '$ 0.00 ',
                                        styleHtmlContent: true,
                                        width: 135
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'Trauma:',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        width: 20
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '$ 0.00 ',
                                        styleHtmlContent: true,
                                        width: 135
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'Disability',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        width: 20
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '$ 0.00 ',
                                        styleHtmlContent: true,
                                        width: 135
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 220,
                                        label: 'Involuntary Unemployment:',
                                        labelAlign: 'right',
                                        labelWidth: '78%'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        width: 5
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '$ 0.00 ',
                                        styleHtmlContent: true,
                                        width: 135
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'left',
                                        width: 145,
                                        label: 'None:',
                                        labelAlign: 'right',
                                        labelWidth: '70%'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        docked: 'left',
                        height: 320,
                        width: 150,
                        items: [
                            {
                                xtype: 'container',
                                height: 120,
                                width: 150
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 150,
                                items: [
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: 30,
                                        width: 30,
                                        text: 'i'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'RS: 67',
                                        styleHtmlContent: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 150,
                                items: [
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        width: 30
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'RC: 2767',
                                        styleHtmlContent: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 320,
                        width: 290,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                width: '99%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'COPL Insurance',
                                        padding: 5,
                                        width: 163
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Amount Financed:',
                                        styleHtmlContent: true,
                                        width: 132
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '2,356.00',
                                        styleHtmlContent: true,
                                        width: 30
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'right',
                                        html: 'Excl. PPI',
                                        styleHtmlContent: true,
                                        width: 90
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Balloon Residual:',
                                        styleHtmlContent: true,
                                        width: 132
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '0.00 ',
                                        styleHtmlContent: true,
                                        width: 30
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Payment Frequency:',
                                        styleHtmlContent: true,
                                        width: 173
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '0.00 ',
                                        styleHtmlContent: true,
                                        width: 87
                                    }
                                ]
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                disabled: true,
                                disabledCls: ' ',
                                inputCls: 'textBlack',
                                label: 'Insure Term (mths):',
                                labelCls: 'normalLabelText',
                                labelWidth: '60%'
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 290,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Finance Term:',
                                        styleHtmlContent: true,
                                        width: 173
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '',
                                        styleHtmlContent: true,
                                        width: 87
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                height: 45,
                items: [
                    {
                        xtype: 'label',
                        docked: 'left',
                        html: 'CCI Period of Cover:',
                        styleHtmlContent: true
                    },
                    {
                        xtype: 'datepickerfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        disabled: true,
                        disabledCls: ' ',
                        docked: 'left',
                        height: 45,
                        width: 220,
                        inputCls: 'textBlack',
                        label: 'From:',
                        labelCls: 'normalLabelText',
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'datepickerfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        disabled: true,
                        disabledCls: ' ',
                        docked: 'left',
                        height: 45,
                        width: 220,
                        inputCls: 'textBlack',
                        label: 'To:',
                        labelCls: 'normalLabelText',
                        placeHolder: 'mm/dd/yyyy'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                height: 320,
                items: [
                    {
                        xtype: 'panel',
                        docked: 'left',
                        height: 320,
                        width: '100%',
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'COPL Insurance',
                                        padding: 5,
                                        width: 163
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        width: 350,
                                        inputCls: 'textBlack',
                                        label: 'Vehicle Rego Number:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Credit Provider:',
                                        styleHtmlContent: true,
                                        width: 210
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'ANZ Banking Group ltd.',
                                        styleHtmlContent: true,
                                        width: 249
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Loan Commencement Date:',
                                        styleHtmlContent: true,
                                        width: 220
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '26/06/2012',
                                        styleHtmlContent: true,
                                        width: 143
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '* must be same as insurance cover date ',
                                        styleHtmlContent: true,
                                        width: 360
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        width: 350,
                                        inputCls: 'textBlack',
                                        label: 'Loan Contract Number:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: 'Type of Contract:',
                                        styleHtmlContent: true
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 740,
                                items: [
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 130,
                                        inputCls: 'textBlack',
                                        label: 'Regulated',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 170,
                                        inputCls: 'textBlack',
                                        label: 'Hire Purchase',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 120,
                                        inputCls: 'textBlack',
                                        label: 'Lease',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '60%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 190,
                                        inputCls: 'textBlack',
                                        label: 'Chattal Mortgage',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '70%',
                                        name: 'contracttype'
                                    },
                                    {
                                        xtype: 'radiofield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 130,
                                        inputCls: 'textBlack',
                                        label: 'Cash Deal',
                                        labelAlign: 'right',
                                        labelCls: 'normalLabelTextRadio',
                                        labelWidth: '60%',
                                        name: 'contracttype'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5,
                width: 730
            },
            {
                xtype: 'container',
                height: 5,
                width: 730,
                items: [
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 400,
                        width: 350,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '1st Insured',
                                        padding: 5,
                                        width: 144
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'right',
                                        width: 190,
                                        label: 'Client Age OK',
                                        labelWidth: '70%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Status:',
                                        options: [
                                            {
                                                value: 'FT',
                                                text: 'Full Time'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Employer:'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Occupation:',
                                        options: [
                                            {
                                                value: 'PE',
                                                text: 'Professional/Exective'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Hours per week:'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Employ period (mths):'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Medical Condition to declare:',
                                        options: [
                                            {
                                                value: 'Y',
                                                text: 'Y'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'If YES enter details:'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 30
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 400,
                        width: 350,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        html: '2nd Insured',
                                        padding: 5,
                                        width: 144
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        docked: 'right',
                                        width: 190,
                                        label: 'Client Age OK',
                                        labelWidth: '70%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Status:',
                                        options: [
                                            {
                                                value: 'FT',
                                                text: 'Full Time'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Employer:'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Occupation:',
                                        options: [
                                            {
                                                value: 'PE',
                                                text: 'Professional/Exective'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Hours per week:'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Employ period (mths):'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'Medical Condition to declare:',
                                        options: [
                                            {
                                                value: 'Y',
                                                text: 'Y'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                width: 350,
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        cls: [
                                            'textBlack'
                                        ],
                                        label: 'If YES enter details:'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});