/*
 * File: app/view/Customer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Customer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.customer',

    config: {
        ui: 'light',
        iconCls: 'customer',
        title: 'Customer',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Customer',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 93,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 87,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 88,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'panel',
                items: [
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 150,
                        inputCls: 'textBlack',
                        label: 'Private',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'prvtbusgroup',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 150,
                        inputCls: 'textBlack',
                        label: 'Business',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'prvtbusgroup'
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 180,
                        inputCls: 'textBlack',
                        label: 'Single Name',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'sngljointgroup',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 180,
                        inputCls: 'textBlack',
                        label: 'Joint Names',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'sngljointgroup'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'panel',
                hidden: true,
                items: [
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        height: 37,
                        width: 185,
                        label: 'Regulated',
                        labelAlign: 'right',
                        labelWidth: '70%',
                        name: 'radiogroup'
                    },
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        label: 'Hire Purchase',
                        labelAlign: 'right',
                        labelWidth: '70%',
                        name: 'radiogroup'
                    },
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        label: 'Lease',
                        labelAlign: 'right',
                        labelWidth: '70%',
                        name: 'radiogroup'
                    },
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        width: 218,
                        label: 'Chattal Mortgage',
                        labelAlign: 'right',
                        labelWidth: '70%',
                        name: 'radiogroup'
                    },
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        label: 'Cash Deal',
                        labelAlign: 'right',
                        labelWidth: '70%',
                        name: 'radiogroup'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                html: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        height: 30,
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Private Street Address(1st Insured)',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 225,
                                inputCls: 'textBlack',
                                label: 'Title:',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%',
                                options: [
                                    {
                                        value: 'Mr',
                                        text: 'Mr.'
                                    },
                                    {
                                        value: 'Ms',
                                        text: 'Ms.'
                                    },
                                    {
                                        value: 'Mrs',
                                        text: 'Mrs.'
                                    },
                                    {
                                        value: 'D',
                                        text: 'Dr.'
                                    },
                                    {
                                        value: 'P',
                                        text: 'Professor.'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 5
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: 'Gender:',
                                padding: 5,
                                width: 68
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 102,
                                inputCls: 'textBlack',
                                label: 'Male',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '55%',
                                name: 'gendergroup',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 120,
                                inputCls: 'textBlack',
                                label: 'Female',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '62%',
                                name: 'gendergroup'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 6
                            },
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 213,
                                inputCls: 'textBlack',
                                label: 'Registered for GST?',
                                labelCls: 'normalLabelText',
                                labelWidth: '64%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'Y',
                                        text: 'Yes'
                                    },
                                    {
                                        value: 'N',
                                        text: 'No'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'First Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '45%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 245,
                                inputCls: 'textBlack',
                                label: 'Middle  Name:',
                                labelCls: 'normalLabelText',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 243,
                                inputCls: 'textBlack',
                                label: 'Last  Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '45%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'emailfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 300,
                                inputCls: 'textBlack',
                                label: 'Email:',
                                labelCls: 'normalLabelText',
                                placeHolder: 'email@example.com'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'Home #:',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%'
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 245,
                                inputCls: 'textBlack',
                                label: 'Business #:',
                                labelCls: 'normalLabelText',
                                labelWidth: '50%'
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 245,
                                inputCls: 'textBlack',
                                label: 'Mobile #:',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'Street No:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                width: 490,
                                inputCls: 'textBlack',
                                label: 'Street Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '25%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'Suburb:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 292,
                                inputCls: 'textBlack',
                                label: 'State:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '25%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'ACT',
                                        text: 'Australian Capital Territory'
                                    },
                                    {
                                        value: 'NSW',
                                        text: 'New South Wales'
                                    },
                                    {
                                        value: 'SA',
                                        text: 'South Australia'
                                    }
                                ]
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 199,
                                inputCls: 'textBlack',
                                label: 'Postal Code:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '57%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 40,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'ABN:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 34,
                                width: 291
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 200,
                                inputCls: 'textBlack',
                                label: 'DOB:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 15
                    },
                    {
                        xtype: 'panel',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 20,
                                html: 'Private Mail Address'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'textBlack'
                                ],
                                height: 45,
                                width: 300,
                                label: 'Same as Street Address?',
                                labelAlign: 'right',
                                labelWidth: '80%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'Street No:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 493,
                                inputCls: 'textBlack',
                                label: 'Stree Name:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '25%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'panel',
                        height: 45,
                        items: [
                            {
                                xtype: 'textfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 250,
                                inputCls: 'textBlack',
                                label: 'Suburb:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 292,
                                inputCls: 'textBlack',
                                label: 'State:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '25%',
                                options: [
                                    {
                                        value: 'null',
                                        text: 'Select'
                                    },
                                    {
                                        value: 'ACT',
                                        text: 'Australian Capital Territory'
                                    },
                                    {
                                        value: 'NSW',
                                        text: 'New South Wales'
                                    },
                                    {
                                        value: 'SA',
                                        text: 'South Australia'
                                    }
                                ]
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 201,
                                inputCls: 'textBlack',
                                label: 'Postal Code:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '57%'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});