/*
 * File: app/view/Finance.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Finance', {
    extend: 'Ext.form.Panel',
    alias: 'widget.finance',

    config: {
        ui: 'light',
        iconCls: 'finance',
        iconMask: 'true',
        title: 'Finance',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Finance',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 105,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 85,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 45,
                items: [
                    {
                        xtype: 'selectfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        id: 'financier',
                        itemId: 'financier',
                        width: 329,
                        inputCls: 'textBlack',
                        label: 'Financier:',
                        labelCls: 'normalLabelText',
                        labelWidth: '35%',
                        options: [
                            {
                                value: 'null',
                                text: 'Select'
                            },
                            {
                                value: 'ANZ',
                                text: 'ANZ Banking group ltd.'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 8
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'Stamp Duty State:',
                        width: 153
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'NSW',
                        width: 57
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'RT:',
                        width: 44
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 10.45,
                        width: 57
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        height: 19,
                        width: 10
                    },
                    {
                        xtype: 'image',
                        docked: 'left',
                        height: 25,
                        width: 71,
                        src: 'images/statusfalse.png'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'panel',
                height: 45,
                items: [
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        height: 45,
                        width: 331
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'From:',
                        width: 66
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: '06/06/2012',
                        width: 113
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'To:',
                        width: 44
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: '05/06/2015',
                        width: 110
                    }
                ]
            },
            {
                xtype: 'panel',
                height: 45,
                items: [
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        id: 'rdRegulated',
                        itemId: 'myradiobutton27',
                        width: 140,
                        inputCls: 'textBlack',
                        label: 'Regulated',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '67%',
                        name: 'productType',
                        value: 'R',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        itemId: 'rdHirePurchase',
                        width: 150,
                        inputCls: 'textBlack',
                        label: 'Hire Purchase',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '67%',
                        name: 'productType',
                        value: 'H'
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        id: 'rdLease',
                        itemId: 'myradiobutton29',
                        width: 109,
                        inputCls: 'textBlack',
                        label: 'Lease',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '65%',
                        name: 'productType',
                        value: 'L'
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        id: 'rdChattalMortgage',
                        itemId: 'myradiobutton30',
                        width: 204,
                        inputCls: 'textBlack',
                        label: 'Chattel Mortgage',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '75%',
                        name: 'productType',
                        value: 'M'
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        id: 'rdCashDeal',
                        itemId: 'myradiobutton31',
                        width: 142,
                        inputCls: 'textBlack',
                        label: 'Cash Deal',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '68%',
                        name: 'productType',
                        value: 'C'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'panel',
                height: 45,
                items: [
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        disabled: true,
                        docked: 'left',
                        height: 45,
                        id: 'rdAdvance',
                        width: 140,
                        inputCls: 'textBlack',
                        label: 'Advance',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '70%',
                        name: 'advanceareargroup',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        disabled: true,
                        docked: 'left',
                        height: 45,
                        id: 'rdArrear',
                        width: 137,
                        inputCls: 'textBlack',
                        label: 'Arrear',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '70%',
                        name: 'advanceareargroup',
                        checked: true
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        html: 'Asset Condition:',
                        padding: 5,
                        width: 165
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        id: 'rdNew',
                        width: 151,
                        inputCls: 'textBlack',
                        label: 'New',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '60%',
                        name: 'assetconditiongroup',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        id: 'rdUsed',
                        width: 142,
                        inputCls: 'textBlack',
                        label: 'Used',
                        labelAlign: 'right',
                        labelCls: 'normalLabelTextRadio',
                        labelWidth: '60%',
                        name: 'assetconditiongroup'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'panel',
                cls: [
                    'contentBG'
                ],
                height: 200,
                id: 'assetPriceDetail',
                padding: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                height: 31,
                                html: 'Asset Price(s) Inclusive GST and LCT',
                                padding: 5,
                                width: 369
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        width: 740,
                        items: [
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 319,
                                inputCls: 'textBlack',
                                label: 'Retail Price:',
                                labelCls: 'normalLabelText',
                                labelWidth: '40%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 24,
                                width: 40
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                inputCls: 'textBlack',
                                label: 'Delivery Charges:',
                                labelCls: 'normalLabelText',
                                labelWidth: '45%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Accessories:',
                                padding: 5,
                                width: 113
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.0 ',
                                padding: 5,
                                width: 50
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 48,
                                text: '...'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 25
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'textBlack'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 150,
                                label: 'Fee',
                                labelAlign: 'right',
                                labelWidth: '70%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.0 ',
                                padding: 5,
                                width: 50
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 48,
                                text: '...'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'textBlack'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 181,
                                label: 'After Market',
                                labelAlign: 'right',
                                labelWidth: '75%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.0 ',
                                padding: 5,
                                width: 50
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'textBlack'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 115,
                                label: 'On Road',
                                labelAlign: 'right',
                                labelWidth: '70%'
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.0 ',
                                padding: 5,
                                width: 48
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 48,
                                text: '...'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 25
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'textBlack'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 150,
                                label: 'Insurance',
                                labelAlign: 'right',
                                labelWidth: '70%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 26,
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.0 ',
                                padding: 5,
                                width: 50
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 48,
                                text: '...'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    }
                ]
            },
            {
                xtype: 'container',
                height: 1
            },
            {
                xtype: 'panel',
                cls: [
                    'contentBG'
                ],
                height: 145,
                id: 'deposit',
                padding: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                height: 31,
                                html: 'Deposit',
                                padding: 5,
                                width: 369
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Trade In:',
                                padding: 5,
                                width: 128
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.00 ',
                                padding: 5,
                                width: 50
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 48,
                                text: '...'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 26
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 215,
                                inputCls: 'textBlack',
                                label: 'Deposit:',
                                labelCls: 'normalLabelText',
                                labelWidth: '50%',
                                value: 0
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 29
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Total Deposit:',
                                width: 127
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 53
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.00 ',
                                padding: 5,
                                width: 50
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Amount Financed:',
                                padding: 5,
                                width: 159
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.00 ',
                                padding: 5,
                                width: 67
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 31
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 1
            },
            {
                xtype: 'panel',
                cls: [
                    'contentBG'
                ],
                height: 199,
                id: 'payments',
                padding: '',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        ui: 'light',
                        width: '100%',
                        items: [
                            {
                                xtype: 'label',
                                height: 31,
                                html: 'Payments:',
                                padding: 5,
                                width: 369
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'selectfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 275,
                                inputCls: 'textBlack',
                                label: 'Payment Frequency:',
                                labelCls: 'normalLabelText',
                                labelWidth: '52%',
                                options: [
                                    {
                                        value: 'Y',
                                        text: 'Yearly'
                                    },
                                    {
                                        value: 'M',
                                        text: 'Monthly'
                                    },
                                    {
                                        value: 'W',
                                        text: 'Weekly'
                                    },
                                    {
                                        value: 'F',
                                        text: 'Fortnightly'
                                    },
                                    {
                                        value: 'Q',
                                        text: 'Quarterly'
                                    },
                                    {
                                        value: 'H',
                                        text: 'Half Yearly'
                                    }
                                ]
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 13
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 225,
                                inputCls: 'textBlack',
                                label: 'Term:',
                                labelCls: 'normalLabelText',
                                labelWidth: '58%',
                                value: 36
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 220,
                                inputCls: 'textBlack',
                                label: 'Balloon Percentage:',
                                labelCls: 'normalLabelText',
                                labelWidth: '65%'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 275,
                                inputCls: 'textBlack',
                                label: 'Payments:',
                                labelCls: 'normalLabelText',
                                labelWidth: '52%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 15
                            },
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 225,
                                inputCls: 'textBlack',
                                label: 'Balloon Amount:',
                                labelCls: 'normalLabelText',
                                labelWidth: '60%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'GST on Rental Amount: ',
                                padding: 5,
                                width: 166
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.00 ',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 5
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 238,
                                inputCls: 'textBlack',
                                label: 'Maintenance Fee:',
                                labelCls: 'normalLabelText',
                                labelWidth: '60%'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 40,
                                width: 38,
                                text: '...'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 40,
                                width: 16
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Total Payment:',
                                padding: 5,
                                width: 145
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: '0.00 ',
                                padding: 5,
                                width: 60
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                width: 10
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 45,
                                html: 'Weekly Equivalent:',
                                padding: 5,
                                width: 173
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: '0.00 ',
                                padding: 5,
                                width: 54
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onRdRegulatedCheck',
                event: 'check',
                delegate: '#rdRegulated'
            },
            {
                fn: 'onHirePurchaseHandler',
                event: 'check',
                delegate: '#rdHirePurchase'
            },
            {
                fn: 'onRdLeaseCheck',
                event: 'check',
                delegate: '#rdLease'
            },
            {
                fn: 'onRdChattalMortgageCheck',
                event: 'check',
                delegate: '#rdChattalMortgage'
            },
            {
                fn: 'onRdCashDealCheck',
                event: 'check',
                delegate: '#rdCashDeal'
            }
        ]
    },

    onRdRegulatedCheck: function(checkboxfield, e, options) {
        Ext.getCmp("rdAdvance").setHidden(false);
        Ext.getCmp("rdArrear").setHidden(false);

        Ext.getCmp("rdAdvance").setDisabled(true);
        Ext.getCmp("rdArrear").setDisabled(true);
        Ext.getCmp("rdArrear").setChecked(true);
    },

    onHirePurchaseHandler: function(checkboxfield, e, options) {

        //Ext.Msg.alert('getGroupValue()', this.getValues().productType);

        Ext.getCmp("rdAdvance").setHidden(false);
        Ext.getCmp("rdArrear").setHidden(false);

        Ext.getCmp("rdAdvance").setDisabled(false);
        Ext.getCmp("rdArrear").setDisabled(false);
        Ext.getCmp("rdArrear").setChecked(true);


    },

    onRdLeaseCheck: function(checkboxfield, e, options) {
        Ext.getCmp("rdAdvance").setHidden(false);
        Ext.getCmp("rdArrear").setHidden(false);

        Ext.getCmp("rdAdvance").setDisabled(false);
        Ext.getCmp("rdArrear").setDisabled(false);
        Ext.getCmp("rdAdvance").setChecked(true);
    },

    onRdChattalMortgageCheck: function(checkboxfield, e, options) {
        Ext.getCmp("rdAdvance").setHidden(false);
        Ext.getCmp("rdArrear").setHidden(false);


        Ext.getCmp("rdAdvance").setDisabled(false);
        Ext.getCmp("rdArrear").setDisabled(false);
        Ext.getCmp("rdArrear").setChecked(true);
    },

    onRdCashDealCheck: function(checkboxfield, e, options) {

        Ext.getCmp("rdAdvance").setHidden(true);
        Ext.getCmp("rdArrear").setHidden(true);

        Ext.getCmp("rdAdvance").setChecked(false);
        Ext.getCmp("rdArrear").setChecked(false);
    }

});