/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.LoginForm',

    config: {
        styleHtmlContent: true,
        ui: 'dark',
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        scrollable: false,
        cls: [
            'contentBGSquare'
        ],
        items: [
            {
                xtype: 'fieldset',
                border: 2,
                centered: true,
                cls: [
                    'loginBG'
                ],
                height: 398,
                html: '<body background="images/bg.png"></body>',
                padding: '',
                ui: 'dark',
                width: 500,
                title: 'iOS Android Application',
                layout: {
                    align: 'center',
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 85,
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 21,
                                ui: '',
                                width: 200
                            },
                            {
                                xtype: 'label',
                                cls: [
                                    'productName'
                                ],
                                draggable: true,
                                height: 96,
                                html: '<font color="#538CBE" size="4" align=right><b>FINANCE AND<br /> INSURANCE<br /> APPLICATION</b></font>',
                                id: '',
                                left: '',
                                padding: '',
                                styleHtmlContent: true,
                                top: '',
                                ui: '',
                                width: 213
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 21,
                                ui: '',
                                width: 78
                            },
                            {
                                xtype: 'label',
                                cls: [
                                    'productVersion'
                                ],
                                docked: 'left',
                                height: 31,
                                html: '<b><font color="#FD803D">Version  1.00.00 build 120625</font></b>',
                                styleHtmlContent: true,
                                width: 251
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: [
                            'textInput'
                        ],
                        height: 116,
                        items: [
                            {
                                xtype: 'textfield',
                                border: '',
                                cls: [
                                    'inputBorder'
                                ],
                                height: 45,
                                id: 'userID',
                                itemId: 'userID',
                                padding: '',
                                style: 'border=2',
                                width: 374,
                                label: 'User Name:',
                                labelWidth: '50%',
                                value: 'mcopl001'
                            },
                            {
                                xtype: 'passwordfield',
                                border: '',
                                bottom: '',
                                cls: [
                                    'inputBorder'
                                ],
                                height: 45,
                                padding: 5,
                                width: 374,
                                label: 'Password:',
                                labelWidth: '50%',
                                value: 'flying098'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 21,
                                ui: '',
                                width: 272
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 21,
                                ui: '',
                                width: 272
                            },
                            {
                                xtype: 'button',
                                cls: 'cutomButtonBlue',
                                docked: 'left',
                                height: 55,
                                ui: 'action-small',
                                width: 120,
                                text: 'Login',
                                action: 'LoginAction'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 12,
                                ui: '',
                                width: 272
                            }
                        ]
                    },
                    {
                        xtype: 'image',
                        height: 86,
                        left: 5,
                        top: 10,
                        width: 86,
                        src: 'images/logo_.png'
                    },
                    {
                        xtype: 'image',
                        bottom: 40,
                        height: 200,
                        left: 5,
                        width: 50,
                        src: 'images/sideLock.png'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onFormpanelShow',
                event: 'show'
            }
        ]
    },

    onFormpanelShow: function(component, options) {
        Ext.getCmp('userID').focus('', 10);
    }

});