/*
 * File: app/view/Summary.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Summary', {
    extend: 'Ext.form.Panel',
    alias: 'widget.summary',

    config: {
        ui: 'light',
        scrollable: 'vertical',
        iconCls: 'summary',
        title: 'Summary',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                style: '',
                ui: 'light',
                title: '',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'Summary',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 104,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 89,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 95,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 86,
                        icon: 'images/next1.png',
                        iconAlign: 'center',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                cls: [
                    'contentBG'
                ],
                html: '',
                ui: 'light',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: [
                            'topRoundCorners'
                        ],
                        docked: 'top',
                        height: 30,
                        ui: 'light',
                        title: '',
                        items: [
                            {
                                xtype: 'label',
                                html: 'Finance',
                                padding: 5
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 35,
                        items: [
                            {
                                xtype: 'numberfield',
                                cls: [
                                    'mandatoryRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                id: 'vehiclePrice',
                                itemId: 'vehiclePrice',
                                minHeight: 45,
                                style: 'inputField',
                                width: 246,
                                clearIcon: false,
                                inputCls: 'textBlackRight',
                                label: 'Vehicle Price:',
                                labelCls: 'mandatoryLabelText',
                                labelWidth: '55%',
                                value: 0.00
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: 'Payments: Monthly: ',
                                width: 161
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 13
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: '  0.00',
                                width: 63
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 13
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 30,
                                html: 'Equivalent Weekly:',
                                width: 158
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 32,
                                html: ' 0.00',
                                width: 65
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 10
                    },
                    {
                        xtype: 'panel',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: 'Loan Period: ',
                                left: '',
                                padding: 5,
                                width: 103
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 16
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 24
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 25,
                                html: ' 0.00',
                                width: 113
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 11
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 30,
                                html: 'From:',
                                width: 52
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 11
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 32,
                                html: '06/06/2012',
                                width: 88
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 30,
                                html: 'To:',
                                width: 51
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 11
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 32,
                                html: '06/06/2012',
                                width: 83
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 13
                            },
                            {
                                xtype: 'checkboxfield',
                                cls: [
                                    'onlyRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 119,
                                inputCls: '',
                                label: 'Display All',
                                labelAlign: 'right',
                                labelCls: '',
                                labelWidth: '70%'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 10
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                height: 35,
                                width: 35,
                                text: 'P'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 15
                    },
                    {
                        xtype: 'container',
                        height: 30,
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 236
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'Monthly'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 86
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'Weekly'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 86
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'Total Premium'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'CCI',
                                padding: 5,
                                width: 47
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                top: '',
                                width: 15,
                                src: ''
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 179
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 58
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 94
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 55
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 105
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 114
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 15
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 88,
                                src: 'images/statusfalse.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'EPI',
                                padding: 5,
                                width: 45
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 15
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 179
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 58
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 94
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 55
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 105
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 114
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 88,
                                src: 'images/statusfalse.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'CBI',
                                padding: 5,
                                width: 46
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 15
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 179
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 58
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 94
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 55
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 105
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 114
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 17
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 88,
                                src: 'images/statusfalse.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 30,
                        items: [
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: 'WTY',
                                padding: 5
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 15
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 180
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 58
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 94
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 55
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 105
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                html: ' 0.0',
                                width: 114
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 18
                            },
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 25,
                                width: 88,
                                src: 'images/statusfalse.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 35
                    },
                    {
                        xtype: 'container',
                        height: 45,
                        items: [
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 16
                            },
                            {
                                xtype: 'datepickerfield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                docked: 'left',
                                height: 45,
                                width: 353,
                                inputCls: 'textBlack',
                                label: 'Forward Date Documents to:',
                                labelCls: 'normalLabelText',
                                labelWidth: '60%',
                                name: '',
                                value: {
                                    year: 2012,
                                    month: 6,
                                    day: 4
                                },
                                placeHolder: 'mm/dd/yyyy',
                                dateFormat: 'd/m/Y'
                            },
                            {
                                xtype: 'spacer',
                                docked: 'left',
                                height: 25,
                                width: 16
                            },
                            {
                                xtype: 'label',
                                docked: 'left',
                                height: 30,
                                html: 'Maximum 5 days',
                                padding: 5,
                                width: 154
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                text: 'Clear'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 46
                    }
                ]
            }
        ]
    }

});