/*
 * File: app/view/WTY.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.WTY', {
    extend: 'Ext.form.Panel',
    alias: 'widget.wty',

    config: {
        ui: 'light',
        iconCls: 'insurance',
        title: 'WTY',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 80,
                ui: 'light',
                items: [
                    {
                        xtype: 'label',
                        height: 31,
                        html: 'WTY',
                        padding: 5,
                        width: 113
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 92,
                        icon: 'images/cancel.png',
                        iconCls: 'cancel',
                        text: 'Cancel',
                        action: 'CancelAction'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 92,
                        icon: 'images/save.png',
                        iconCls: 'save',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 88,
                        icon: 'images/print.png',
                        iconCls: 'print',
                        text: 'Print'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        width: 85,
                        icon: 'images/next1.png'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                height: 45,
                items: [
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'TP Warranty:',
                        width: 118
                    },
                    {
                        xtype: 'button',
                        docked: 'left',
                        height: 40,
                        width: 40,
                        text: '...'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 5
            },
            {
                xtype: 'container',
                height: 45,
                items: [
                    {
                        xtype: 'selectfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 280,
                        inputCls: 'textBlack',
                        label: 'Product Type:',
                        labelCls: 'normalLabelText',
                        labelWidth: '45%',
                        options: [
                            {
                                value: 'null',
                                text: 'None'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'selectfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 189,
                        inputCls: 'textBlack',
                        label: 'Badge:',
                        labelCls: 'normalLabelText',
                        labelWidth: '40%',
                        options: [
                            {
                                value: 'A',
                                text: 'A'
                            },
                            {
                                value: 'M',
                                text: 'M'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'numberfield',
                        cls: [
                            'normalRoundCorner'
                        ],
                        docked: 'left',
                        height: 45,
                        width: 245,
                        inputCls: 'textBlack',
                        label: 'Premium: $',
                        labelCls: 'normalLabelText',
                        labelWidth: '45%'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 45,
                width: 737,
                items: [
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        height: 23,
                        width: 477
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: 'Total Payable Premium:'
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 13
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        height: 45,
                        html: '  0.0',
                        width: 56
                    }
                ]
            },
            {
                xtype: 'container',
                height: 10
            },
            {
                xtype: 'container',
                height: 3
            },
            {
                xtype: 'container',
                height: 270,
                styleHtmlContent: true,
                items: [
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'panel',
                        border: '',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 275,
                        padding: '',
                        width: 182,
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                ui: 'light',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 45,
                                        html: 'Dealer Warranty Plan',
                                        width: 176
                                    }
                                ]
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: '12 months',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'warrantyplangroup',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: '24 months',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'warrantyplangroup'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: '36 months',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'warrantyplangroup'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: '48 months',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'warrantyplangroup'
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: '60 months',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'warrantyplangroup'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        height: 10,
                        width: 5
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 149,
                        padding: '',
                        width: 180,
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                ui: 'light',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 45,
                                        html: 'Vehicle Group',
                                        width: 176
                                    }
                                ]
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: 'Group One',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'vehiclegroup',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                cls: [
                                    'normalRoundCorner'
                                ],
                                height: 45,
                                inputCls: 'textBlack',
                                label: 'Group Two',
                                labelAlign: 'right',
                                labelCls: 'normalLabelTextRadio',
                                labelWidth: '70%',
                                name: 'vehiclegroup'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        height: 10,
                        width: 5
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 260,
                        padding: '',
                        width: 365,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners'
                                ],
                                docked: 'top',
                                height: 45,
                                ui: 'light',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 45,
                                        html: 'Tyre and Wheel',
                                        width: 176
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 5
                            },
                            {
                                xtype: 'container',
                                height: 30,
                                width: 362,
                                items: [
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 24,
                                        width: 265
                                    },
                                    {
                                        xtype: 'image',
                                        docked: 'left',
                                        height: 30,
                                        width: 60,
                                        src: 'images/statusfalse.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 5
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 11
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 183,
                                        inputCls: 'textBlack',
                                        label: 'Tyre and Wheel',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '70%'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 5
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'left',
                                        height: 40,
                                        padding: 5,
                                        width: 40,
                                        text: 'i'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 5
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 40,
                                        html: 'RS: 67',
                                        width: 54
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 15
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 40,
                                        html: 'Rc:',
                                        width: 46
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 11
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 300,
                                        inputCls: 'textBlack',
                                        label: 'Insure Term (mnths):',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 35,
                                items: [
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 21,
                                        width: 11
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 300,
                                        inputCls: 'textBlack',
                                        label: 'PREMIUM:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                height: 3
            },
            {
                xtype: 'container',
                height: 475,
                styleHtmlContent: true,
                items: [
                    {
                        xtype: 'spacer',
                        docked: 'left',
                        width: 10
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'contentBG'
                        ],
                        docked: 'left',
                        height: 475,
                        padding: '',
                        width: 735,
                        items: [
                            {
                                xtype: 'toolbar',
                                cls: [
                                    'topRoundCorners',
                                    'whiteBorder'
                                ],
                                docked: 'top',
                                height: 45,
                                ui: 'light',
                                width: '100%',
                                items: [
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 45,
                                        html: 'Asset Warranty Information',
                                        width: 304
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 5
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'Vehicle purchase date by client:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 24,
                                        width: 14
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        inputCls: 'textBlack',
                                        label: 'Vehicle Use:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%',
                                        options: [
                                            {
                                                value: 'null',
                                                text: 'Select'
                                            },
                                            {
                                                value: 'P',
                                                text: 'Private'
                                            },
                                            {
                                                value: 'C',
                                                text: 'Commercial'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'Warranty policy date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty start date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    },
                                    {
                                        xtype: 'spacer',
                                        docked: 'left',
                                        height: 24,
                                        width: 14
                                    },
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        width: 267,
                                        inputCls: 'textBlack',
                                        label: 'Odometer:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '50%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'datepickerfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        disabledCls: 'normalLabelTextDisabled',
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'First Registration start date:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%',
                                        placeHolder: 'mm/dd/yyyy'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty length:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 45,
                                        html: 'months',
                                        padding: 3,
                                        width: 58
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 80,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 454,
                                        inputCls: 'textBlack',
                                        label: 'Length of statutory warranty:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 50,
                                        html: 'days',
                                        padding: 3,
                                        width: 42
                                    },
                                    {
                                        xtype: 'textareafield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        inputCls: 'textBlack',
                                        label: 'Vehicle modification:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '65%'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 390,
                                        inputCls: 'textBlack',
                                        label: 'Factory warranty expiry:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '60%'
                                    },
                                    {
                                        xtype: 'label',
                                        docked: 'left',
                                        height: 50,
                                        html: 'KM\'s',
                                        padding: 3,
                                        width: 80
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        height: 45,
                                        inputCls: 'textBlack',
                                        label: 'Dealer Service Waiver:',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '65%',
                                        options: [
                                            {
                                                value: 'Y',
                                                text: 'Yes'
                                            },
                                            {
                                                value: 'N',
                                                text: 'No'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                height: 3
                            },
                            {
                                xtype: 'container',
                                height: 45,
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        cls: [
                                            'normalRoundCorner'
                                        ],
                                        docked: 'left',
                                        height: 45,
                                        width: 445,
                                        inputCls: 'textBlack',
                                        label: 'Finance Company:  (if financed)',
                                        labelCls: 'normalLabelText',
                                        labelWidth: '55%'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});