/*
 * File: app/model/CustomerIndividual.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.CustomerIndividual', {
    extend: 'Ext.data.Model',
    alias: 'model.CustomerIndividual',
    uses: [
        'MyApp.model.Customer',
        'MyApp.model.CustomerEmployment',
        'MyApp.model.CustomerExpense',
        'MyApp.model.CustomerIncome',
        'MyApp.model.CustomerVerification',
        'MyApp.model.PersonalInformation'
    ],
    config: {
        belongsTo: {
            model: 'MyApp.model.Customer'
        },
        hasOne: [
            {
                model: 'MyApp.model.CustomerEmployment',
                name: 'customerEmployment'
            },
            {
                model: 'MyApp.model.CustomerExpense',
                name: 'customerExpense'
            },
            {
                model: 'MyApp.model.CustomerIncome',
                name: 'customerIncome'
            },
            {
                model: 'MyApp.model.CustomerVerification',
                name: 'customerVerification'
            },
            {
                model: 'MyApp.model.PersonalInformation',
                name: 'personalInformation'
            }
        ],
        fields: [
            {
                defaultValue: '',
                name: 'gstRegistrationIndicator',
                type: 'string'
            }
        ]
    }
});