/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Application',
        'ApplicationStatusCode',
        'CBIPremium',
        'EPIPremium',
        'LTPPremium',
        'EWPremium',
        'ApplicationFinanceCompany',
        'AgentSalePerson',
        'CCIPremium',
        'Fee',
        'Finance',
        'CustomerCorporate',
        'CustomerIndividual',
        'MVPremium',
        'MEPIPremium',
        'DealData',
        'OtherInsurance',
        'VIPPremium',
        'Customer',
        'ContactInformation',
        'CustomerEmployment',
        'CustomerExpense',
        'CustomerVerification',
        'PersonalInformation',
        'CustomerIncome'
    ],
    views: [
        'MainScreen',
        'Summary',
        'Finance',
        'Asset',
        'Customer',
        'CBI',
        'WTY',
        'MVI',
        'AfterMarket',
        'MainScreenComponent',
        'LoginForm',
        'CCI'
    ],
    name: 'MyApp',
    controllers: [
        'CoplController'
    ],

    launch: function() {

        Ext.create('MyApp.view.LoginForm', {fullscreen: true});
    }

});
