/*
 * File: app/controller/CoplController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.CoplController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.CoplController',
    config: {
        refs: {
            mainScreen: 'MainScreen',
            mainScreenComponent: 'MainScreenComponent',
            loginForm: 'LoginForm'
        },

        control: {
            "button[action=NewQuoteAction]": {
                tap: 'onNewQuoteTap'
            },
            "button[action=OpenQuoteAction]": {
                tap: 'onOpenQuoteTap'
            },
            "button[action=CancelAction]": {
                tap: 'onCancelTap'
            },
            "button[action=LoginAction]": {
                tap: 'onLoginTap'
            },
            "button[action=LogoutAction]": {
                tap: 'onLogoutTap'
            }
        }
    },

    onNewQuoteTap: function(button, e, options) {
        Ext.Viewport.setActiveItem({xtype: 'MainScreen',plugins: 'swipetabs' });
    },

    onOpenQuoteTap: function(formpanel) {
        Ext.Viewport.setActiveItem({xtype: 'MainScreen',plugins: 'swipetabs'});
    },

    onCancelTap: function(button, e, options) {
        Ext.Viewport.setActiveItem({xtype: 'MainScreenComponent'});
    },

    onLoginTap: function(button, e, options) {
        Ext.Viewport.setActiveItem({xtype: 'MainScreenComponent'});
    },

    onLogoutTap: function(button, e, options) {
        Ext.Viewport.setActiveItem({xtype: 'LoginForm'});
    }

});